{
  imports = [
    ./bash.nix
    ./brave.nix
    ./discord.nix
    ./eza.nix
    ./fish.nix
    ./jellyfin-tui.nix
    ./qbittorrent.nix
    ./lazygit.nix
    ./tmux.nix
    ./vscode.nix
    ./wezterm.nix
    ./yazi.nix
    ./zathura.nix
    ./zed-editor.nix
    ./zellij.nix
    ./zen-browser.nix
  ];
}
