{
  imports = [
    ../../common/programs
    ./aegisub.nix
    ./brave.nix
    ./deja-dup.nix
    ./folio.nix
    ./fragments.nix
    ./ghostty.nix
    ./helium.nix
    ./hyprland.nix
    ./keystore-explorer.nix
    ./librewolf.nix
    ./niri.nix
    ./qbittorrent.nix
    ./vaults.nix
    ./wezterm.nix
    ./zen-browser.nix
  ];
}
