{
  imports = [
    ./aegisub.nix
    ./bash.nix
    ./brave.nix
    ./deja-dup.nix
    ./eza.nix
    ./fish.nix
    ./folio.nix
    ./fragments.nix
    ./ghostty.nix
    ./gnupg.nix
    ./keystore-explorer.nix
    ./lazygit.nix
    ./librewolf.nix
    ./qbittorrent.nix
    ./tmux.nix
    ./vaults.nix
    ./wezterm.nix
    ./yazi.nix
    ./zathura.nix
    ./zellij.nix
    ./zen-browser.nix
  ];
}
