{
  imports = [
    ./aegisub.nix
    ./bash.nix
    ./brave.nix
    ./deja-dup.nix
    ./eza.nix
    ./fish.nix
    ./folio.nix
    ./fragments.nix
    ./ghostty.nix
    ./helium.nix
    ./hyprland.nix
    ./jellyfin-tui.nix
    ./keystore-explorer.nix
    ./lazygit.nix
    ./librewolf.nix
    ./niri.nix
    ./omniwm.nix
    ./qbittorrent.nix
    ./tmux.nix
    ./vaults.nix
    ./vscode.nix
    ./wezterm.nix
    ./yazi.nix
    ./zathura.nix
    ./zellij.nix
    ./zen-browser.nix
  ];
}
